from typing import List

import matplotlib.pyplot as plt
import numpy as np

# https://www.worldometers.info/world-population/world-population-by-year/
year = [2023, 2022, 2021, 2020, 2019, 2018, 2017, 2016, 2015, 2014, 2013, 2012, 2011, 2010, 2009, 2008, 2007, 2006, 2005, 2004, 2003, 2002, 2001]
pop_in_bil = [8.04, 7.98, 7.91, 7.84, 7.76, 7.68, 7.60, 7.51, 7.43, 7.34, 7.25, 7.16, 7.07, 6.99, 6.90, 6.81, 6.73, 6.64, 6.56, 6.46, 6.39, 6.31, 6.23]

# Using line plot with .plot()
plt.plot(year, pop_in_bil)
plt.title("Population Growth in 20 Years")
plt.xlabel("Year")
plt.ylabel("Population in Billion")
plt.show()
plt.clf() # Use to clean the plot

# data generated by AI
# Using scatter plot with .scatter()
# Sample data
south_east_asia_countries = ['Indonesia', 'Thailand', 'Malaysia', 'Singapore', 'Philippines', 'Vietnam', 'Myanmar', 'Cambodia', 'Laos', 'Brunei'] # Can be converted to dictionary
south_east_asia_gdp = [4.1, 7.5, 11.4, 65.0, 3.3, 2.7, 1.3, 1.5, 2.6, 78.8]  # in thousands of dollars
south_east_asia_life_expectancy = [71.7, 77.2, 75.9, 83.1, 71.2, 75.3, 66.9, 69.6, 67.9, 75.7]  # years old
south_east_asia_pop = [273.5, 69.8, 32.4, 5.7, 110.8, 97.3, 54.4, 16.7, 7.3, 0.4]  # in millions

np_pop = np.array(south_east_asia_pop)
np_pop *= 2

col = {
    'Indonesia': 'blue',
    'Thailand': 'green',
    'Malaysia': 'red',
    'Singapore': 'cyan',
    'Philippines': 'magenta',
    'Vietnam': 'yellow',
    'Myanmar': 'black',
    'Cambodia': 'purple',
    'Laos': 'orange',
    'Brunei': 'pink'
}
colors = []
for country in south_east_asia_countries:
    colors.append(col[country])

plt.scatter(south_east_asia_gdp, south_east_asia_life_expectancy, s=np_pop, c=colors, alpha=0.8)
plt.xticks(range(0, 81, 15))
plt.yticks(range(60, 86, 5))
plt.grid(True)
plt.title("Life Expectancy vs GDP per Capita in South East Asia")
plt.xlabel("GDP per Capita (in thousands of dollars)")
plt.ylabel("Life Expectancy (in years)")
plt.show()


# Using scatter plot with .scatter()
# Sample data
avg_temp = [25, 26, 23, 27, 30, 33, 32, 34, 33, 35, 31, 35] # Generate 12 random temperatures between 25 and 35
ice_cream_sales = [215, 325, 185, 332, 406, 522, 412, 614, 544, 421, 445, 408]
plt.scatter(avg_temp, ice_cream_sales)
plt.xticks([20, 25, 30, 35], ['20°C', '25°C', '30°C', '35°C'])
plt.yticks([200, 300, 400, 500, 600], ['200 sales', '300 sales', '400 sales', '500 sales', '600 sales'])
plt.title("Ice Cream Sales vs Average Temperature")
plt.xlabel("Average Temperature")
plt.ylabel("Ice Cream Sales")

plt.show()
plt.clf()

# Using histogram plot with .hist()
grade_distribution = [75, 75, 80, 89, 90, 91, 94, 95, 78, 96, 99, 85, 70, 97, 88, 82, 74, 73]
plt.hist(grade_distribution, bins=5, edgecolor='white')
plt.title("Grade Distribution")
plt.xlabel("Grades")
plt.ylabel("Number of students")
plt.show()
